# Generated by Django 2.2.13 on 2022-09-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0012_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='key',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('privatekey', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='block',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
